### ISSUE TITLE
Session order

### ISSUE THREAD

**Issue by mitrussell** [MIT-CAVE/cave_app#81]
Feature request:
Add a way to order sessions. Right now, they appear in the order they are created. If users want to create several sessions, there is no way to manage which order they appear in. Also, when you go to the dashboards and select session to show KPIs, the default order is in the order they were created. You can order them by name, but that sort order is lost each time you visit the dashboard.

Potential ideas: use a hamburger to let users drag and drop, have a sort button that can list them and allow a user to order them.

Potential problems: how do you handle ordering between group sessions?

![Image](https://user-images.githubusercontent.com/47668639/240635121-22b4d2ba-5c3c-4cf8-a0e8-797b6c92b954.jpg)

**Comment by maxtkc** [comment]
My initial thoughts on this (with limited understanding of sessions):

- It would be possible to ungroup the sessions and have them be labeled by the team within the session description. This would mean that the ordering would likely be entirely user based
- Leaving the sessions grouped by teams, they could still be user based ordering, or the order for each team could be shared. The sync would be a little tricky because it's outside of the session sync infrastructure, but I guess that's why there's the refresh button

Regarding ui:
- ordering could be done with up and down buttons, moving a session up or down in the list
- ordering can be done with drag and drop (maybe a nicer interface, but more complicated implementation)

Personally, I think entirely user based with interleaving sessions across different teams makes the most sense, but I don't know the use case very well at all.

**Comment by maxtkc** [comment]
After a few discussions about it, we landed on using a DataGrid and leveraging the filter feature:

[#255](https://github.com/MIT-CAVE/cave_static/pull/255)
